name = "AutoLM"
uuid = "513749c4-1492-45a3-bfbf-e630717bb7f0"
authors = ["Immanuel Diener <imi.diener@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
